### ISSUE TITLE
hard requests vs. soft ?

### ISSUE THREAD

**Issue by annacnev** [ahmedbilal/Class-Scheduling#1]
Hey! I am looking at this code as a template to create something similar. I read the paper that was posted as a resource to this and I was wondering where/how in your code are the hard and soft constraints defined and distinguished? I.e. if I wanted to create another "hard" and soft constraint to add to the model.. how would I do that?

**Comment by annacnev** [comment]
I am trying to add in professor availability constraint as a hard constraint, professor max work hours as a hard constraint, and professor skillset for the course being taught (i.e. if they have taught the course in the past they have experience teaching it and skillset would be higher) as a soft constraint.

**Comment by ahmedbilal** [comment]
@annacnev Thanks for your interest. As far as I remembers, I didn't implements any soft constraint. I only implements hard constraints like
1. Faculty (Professor) must have only one class at a time `def faculty_member_one_class(chromosome)`
2. A group of student (A group is consisted of students that are taking the exact same classes) must have only one class at a time `def group_member_one_class(chromosomes)`
3. Lecture must be in a spare/unfilled room `def use_spare_classroom(chromosome)`
4. Classroom size must be appropriate. i.e We don't want to stuff 100 students in a hall of 30 size. `def classroom_size(chromosomes)`
5. Typical Lecture must be in Lecture theater while Labs should be in Labs. `def appropriate_room(chromosomes)`
6. Lab course must be allocated a longer time slot e.g 3 hours `def appropriate_timeslot(chromosomes)`

A lot of implementation ideas are taken from [Making a Class Schedule using a Genetic Algorithm](https://www.codeproject.com/Articles/23111/Making-a-Class-Schedule-Using-a-Genetic-Algorithm)

I guess that for implementing professor availability, max work hours and skill set you wouldn't need to change the chromosome's structure. Instead, you would need to modify the Professor class to incorporate the availability timings, max hours and skill set (which would be a list of courses). Then, you need to write functions to check whether the allocated <Class, Professor, Student Group, Time Slot, Room> should be feasible by checking professor's availability timing, hours he/she already been engaged and skill set. These function's structure would look similar to the above mentioned functions' structures.

I hope it would help.
